# Generated by Django 4.2.3 on 2023-07-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0002_alter_contacto_numero_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='asunto',
            field=models.CharField(default='sin asunto', max_length=50),
        ),
    ]
