# Generated by Django 4.2.3 on 2023-07-23 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
