# Generated by Django 4.2.3 on 2023-07-25 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_es_miembro_usuario_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='domicilio',
        ),
    ]
