# Generated by Django 4.2.3 on 2023-08-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='fecha_edicion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
