# Generated by Django 4.2.3 on 2023-08-03 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_rename_usuario_comentario_creador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='creador',
            new_name='autor',
        ),
    ]
